# Através do rake é possível implementar o processo de semente, para o cucumber executar uma tarefa para gente.
require "digest/md5"
require_relative "features/support/libs/mongo.rb"
def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end
task :test do
    puts "Executando uma tarefa de teste"
end
task :local_seeds do
    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))
        users = [
            { name: "Roberto Carlos", email: "betao@yahoo.com", password: to_md5("pwd123") },
            { name: "Andreza Silva", email: "andrezasilva744@gmail.com", password: to_md5("pwd123") },
            { name: "Anderson Silva", email: "spider@hotmail.com", password: to_md5("pwd123") },
            #roda uma vez só antes de fazer o teste
          ]
          MongoDB.new.drop_danger
          MongoDB.new.insert_users(users)
          # sh "cucumber"  
end 
task :hmg_seeds do
    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))
        users = [
            { name: "Roberto Carlos", email: "betao@yahoo.com", password: to_md5("pwd123") },
            { name: "Andreza Silva", email: "andrezasilva744@gmail.com", password: to_md5("pwd123") },
          ]
          MongoDB.new.drop_danger
          MongoDB.new.insert_users(users)  
end 